# -*- coding: utf-8 -*-
"""X_infinity_X_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ffs81bpXjuLBTjemYmFQAatFj9yT-wKV
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import pandas as pd
import numpy as np
import requests
import random
from torch.utils.data import Dataset, DataLoader
from transformers import GPT2Model, GPT2Tokenizer
from sklearn.preprocessing import MinMaxScaler
from tqdm import tqdm
import warnings

warnings.filterwarnings("ignore")

# ==========================================
# 1. HYPERPARAMETERS & ALPHAZERO CONFIG
# ==========================================
TS_FEATURES = 2
TS_SEQ_LEN = 60
FORECAST_HORIZON = 12
EPOCHS = 1
BATCH_SIZE = 4

# --- Q* / ALPHAZERO ACTION SPACE ---
# We discretize the temperature shift into 201 actions
# representing scaled changes from -1.0 to +1.0
NUM_ACTIONS = 201
ACTION_MIN = -1.0
ACTION_MAX = 1.0
C_PUCT = 1.25   # AlphaZero exploration constant for Q* Search

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
action_space = torch.linspace(ACTION_MIN, ACTION_MAX, NUM_ACTIONS).to(device)

# ==========================================
# 2. DATA PIPELINE (FORWARD-LOOKING)
# ==========================================
print("Fetching 90 days of TS data (Temperature + Humidity) from Open-Meteo...")
LAT, LON = 40.7128, -74.0060
url = f"https://api.open-meteo.com/v1/forecast?latitude={LAT}&longitude={LON}&past_days=90&hourly=temperature_2m,relative_humidity_2m&timezone=auto"
response = requests.get(url).json()

ts_df = pd.DataFrame({
    'timestamp': pd.to_datetime(response['hourly']['time']),
    'Temperature': response['hourly']['temperature_2m'],
    'Humidity': response['hourly']['relative_humidity_2m']
})
ts_df = ts_df.dropna().set_index('timestamp').sort_index()
ts_df.index = ts_df.index.tz_localize(None)

ts_df['Future_Change'] = ts_df['Temperature'].shift(-FORECAST_HORIZON) - ts_df['Temperature']
ts_df = ts_df.dropna(subset=['Future_Change'])

p10 = ts_df['Future_Change'].quantile(0.10)
p40 = ts_df['Future_Change'].quantile(0.40)
p60 = ts_df['Future_Change'].quantile(0.60)
p90 = ts_df['Future_Change'].quantile(0.90)

def get_dense_freetext(x):
    hot_phrases =["massive heat front", "scorching temperatures", "unprecedented warming", "boiling heatwave"]
    cold_phrases =["severe arctic blast", "drastic drop in temperatures", "freezing blizzard", "sub-zero tundra"]
    stable_phrases =["completely stable", "mild and calm", "normal diurnal weather", "no significant changes"]

    hot = 1.0 if x >= p90 else (0.0 if x <= p60 else (x - p60) / (p90 - p60))
    cold = 1.0 if x <= p10 else (0.0 if x >= p40 else (p40 - x) / (p40 - p10))

    if hot > 0.6 and hot > cold:
        return f"Meteorologists warn of a {random.choice(hot_phrases)} approaching the area over the next 12 hours."
    elif cold > 0.6 and cold > hot:
        return f"Expect a {random.choice(cold_phrases)} moving in rapidly over the next 12 hours."
    else:
        return f"Conditions remain {random.choice(stable_phrases)}."

ts_df['text'] = ts_df['Future_Change'].apply(get_dense_freetext)
ts_df = ts_df.drop(columns=['Future_Change'])

temp_scaler = MinMaxScaler()
hum_scaler = MinMaxScaler()

ts_df['Scaled_Temp'] = temp_scaler.fit_transform(ts_df[['Temperature']])
ts_df['Scaled_Hum'] = hum_scaler.fit_transform(ts_df[['Humidity']])

print("Loading GPT-2 XL Tokenizer & Base Model...")
tokenizer = GPT2Tokenizer.from_pretrained('gpt2-xl')
tokenizer.pad_token = tokenizer.eos_token
gpt2_base = GPT2Model.from_pretrained('gpt2-xl').to(device)

class WeatherQuantumDataset(Dataset):
    def __init__(self, ts_df, tokenizer, ts_seq_len=60, horizon=12):
        self.ts_df = ts_df
        self.tokenizer = tokenizer
        self.ts_seq_len = ts_seq_len
        self.horizon = horizon
        self.ts_values = self.ts_df[['Scaled_Temp', 'Scaled_Hum']].values
        self.text_values = self.ts_df['text'].values

    def __len__(self):
        return len(self.ts_values) - self.ts_seq_len - self.horizon

    def __getitem__(self, idx):
        ts_window = self.ts_values[idx : idx + self.ts_seq_len]
        current_idx = idx + self.ts_seq_len - 1
        target_idx = current_idx + self.horizon

        target_val = self.ts_values[target_idx, 0]
        latest_text = self.text_values[current_idx]

        encoded_text = self.tokenizer(latest_text, padding='max_length', truncation=True, max_length=128, return_tensors='pt')
        return (encoded_text['input_ids'].squeeze(),
                encoded_text['attention_mask'].squeeze(),
                torch.FloatTensor(ts_window),
                torch.FloatTensor([target_val]))

dataset = WeatherQuantumDataset(ts_df, tokenizer, ts_seq_len=TS_SEQ_LEN, horizon=FORECAST_HORIZON)
dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

# ==========================================
# 3. ARCHITECTURE (Q* / ALPHAZERO STYLE)
# ==========================================
class CrossAttentionFusion(nn.Module):
    def __init__(self, d_model, n_heads=8):
        super().__init__()
        self.q_proj = nn.Linear(d_model, d_model)
        self.k_proj = nn.Linear(1600, d_model)
        self.v_proj = nn.Linear(1600, d_model)
        self.mha = nn.MultiheadAttention(d_model, n_heads, batch_first=True, dropout=0.0)
        self.mix = nn.Linear(d_model * 2, d_model)
        self.norm = nn.LayerNorm(d_model)

    def forward(self, state_hidden, text_sequences):
        q = self.q_proj(state_hidden)
        k = self.k_proj(text_sequences)
        v = self.v_proj(text_sequences)
        attn_out, _ = self.mha(q, k, v)
        fused = self.mix(torch.cat([state_hidden, attn_out], dim=-1))
        return self.norm(fused)

class AlphaZero_QStar_Weather(nn.Module):
    def __init__(self, base_model, ts_features=2, d_model=128):
        super().__init__()
        self.gpt2 = base_model
        for param in self.gpt2.parameters(): param.requires_grad = False
        for param in self.gpt2.h[-2:].parameters(): param.requires_grad = True

        # LSTM Replaced with 1D-CNN Feature Extractor to build the "State"
        self.ts_extractor = nn.Sequential(
            nn.Conv1d(ts_features, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.Conv1d(64, d_model, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.AdaptiveAvgPool1d(1) # Flatten sequence to a single State vector
        )

        self.fusion = CrossAttentionFusion(d_model)

        # --- ALPHAZERO DUAL HEADS ---
        # 1. Policy Head P(s, a): Probabilities of which action (temp shift) to take
        self.policy_head = nn.Sequential(
            nn.Linear(d_model, 256), nn.GELU(), nn.Linear(256, NUM_ACTIONS)
        )

        # 2. Value Head Q(s, a): Expected Reward (Accuracy) for every action
        self.value_head = nn.Sequential(
            nn.Linear(d_model, 256), nn.GELU(), nn.Linear(256, NUM_ACTIONS)
        )

    def forward(self, ids, mask, ts):
        gpt2_out = self.gpt2(ids, attention_mask=mask)
        tokens = gpt2_out.last_hidden_state

        # Encode TS State: (B, Seq, Feat) -> (B, Feat, Seq) for Conv1d
        ts_state = self.ts_extractor(ts.permute(0, 2, 1)).permute(0, 2, 1)

        # Fused State $s$
        fused_state = self.fusion(ts_state, tokens).squeeze(1)

        # Outputs P(s, a) and Q(s, a)
        policy_logits = self.policy_head(fused_state)
        q_values = self.value_head(fused_state)
        return policy_logits, q_values

# ==========================================
# 4. TRAINING (DUAL-LOSS RL CLONING)
# ==========================================
model = AlphaZero_QStar_Weather(base_model=gpt2_base).to(device)

optimizer = optim.AdamW([
    {'params': model.gpt2.parameters(), 'lr': 5e-5},
    {'params': model.ts_extractor.parameters(), 'lr': 1e-4},
    {'params': model.fusion.parameters(), 'lr': 5e-4},
    {'params': model.policy_head.parameters(), 'lr': 1e-4},
    {'params': model.value_head.parameters(), 'lr': 1e-4}
])

print(f"AlphaZero Model Initialized. Trainable Params: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")

for epoch in range(EPOCHS):
    model.train()
    loop = tqdm(dataloader, desc=f"Epoch {epoch+1}")
    for ids, mask, ts, y in loop:
        ids, mask, ts, y = ids.to(device), mask.to(device), ts.to(device), y.to(device)
        optimizer.zero_grad()

        policy_logits, q_values = model(ids, mask, ts)

        # --- Q-LEARNING MATHEMATICS ---
        # Calculate true Delta T
        current_temp_scaled = ts[:, -1, 0]
        true_delta = y.squeeze(-1) - current_temp_scaled

        # Map True Delta to Target Action Bin for the Policy Head
        target_action = ((true_delta - ACTION_MIN) / (ACTION_MAX - ACTION_MIN) * (NUM_ACTIONS - 1)).round().long()
        target_action = torch.clamp(target_action, 0, NUM_ACTIONS - 1)

        # Calculate True Q-Values (Reward) for ALL actions
        # Reward = Negative absolute error. Perfect guess = 0 error.
        all_actions = action_space.unsqueeze(0).repeat(ts.size(0), 1)
        true_q_values = -torch.abs(all_actions - true_delta.unsqueeze(1))

        # Dual Losses
        loss_policy = F.cross_entropy(policy_logits, target_action)
        loss_value = F.mse_loss(q_values, true_q_values)
        loss = loss_policy + loss_value

        loss.backward()
        optimizer.step()
        loop.set_postfix(Pol_L=loss_policy.item(), Val_L=loss_value.item())

# ==========================================
# 5. Q* PUCT SEARCH INFERENCE
# ==========================================
def q_star_search_inference(lat, lon, headline):
    model.eval()

    url = f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&past_days=5&hourly=temperature_2m,relative_humidity_2m&timezone=auto"
    response = requests.get(url).json()

    data = pd.DataFrame({
        'timestamp': pd.to_datetime(response['hourly']['time']),
        'Temperature': response['hourly']['temperature_2m'],
        'Humidity': response['hourly']['relative_humidity_2m']
    }).dropna().set_index('timestamp')

    raw_temps = data['Temperature'].values[-60:].reshape(-1, 1)
    raw_hums = data['Humidity'].values[-60:].reshape(-1, 1)

    temps = temp_scaler.transform(raw_temps)
    hums = hum_scaler.transform(raw_hums)

    combined_features = np.concatenate([temps, hums], axis=1)
    ts_input = torch.FloatTensor(combined_features).unsqueeze(0).to(device)

    encoded = tokenizer(headline, padding='max_length', truncation=True, max_length=128, return_tensors='pt')
    ids, mask = encoded['input_ids'].to(device), encoded['attention_mask'].to(device)

    with torch.no_grad():
        with torch.autocast(device_type="cuda" if torch.cuda.is_available() else "cpu", dtype=torch.bfloat16):
            policy_logits, q_values = model(ids, mask, ts_input)

            # --- Q* (PUCT) SEARCH EQUATION ---
            # Score(s, a) = Q(s, a) + C_PUCT * P(s, a)
            policy_probs = F.softmax(policy_logits, dim=-1)
            puct_scores = q_values + C_PUCT * policy_probs

            # Select best action via Tree Search
            best_action_idx = torch.argmax(puct_scores, dim=-1).item()
            best_delta_scaled = action_space[best_action_idx].item()

            current_scaled = ts_input[0, -1, 0].item()
            target_scaled = current_scaled + best_delta_scaled

    # Convert back to real temperature
    pred_actual = temp_scaler.inverse_transform([[target_scaled]])[0][0]
    return float(pred_actual), float(data['Temperature'].iloc[-1].item())

# Generate completely unseen abstract text
hot_news = "It is too hot outside"
mild_news = "Conditions seem completely stable."
cold_news = "Why does it have such a cold weather"

print("\nExecuting Q* Search inference paths...")
hot_p, cur = q_star_search_inference(LAT, LON, hot_news)
mild_p, _  = q_star_search_inference(LAT, LON, mild_news)
cold_p, _  = q_star_search_inference(LAT, LON, cold_news)

print("\n" + "="*50)
print(f"🧠 ALPHAZERO / Q* FREETEXT SEARCH FOR WEATHER (NYC)")
print("="*50)
print(f"Current Temperature:     {cur:.2f}°C")
print(f"Hot Policy+Value Target: {hot_p:.2f}°C")
print(f"Mild Policy+Value Target:{mild_p:.2f}°C")
print(f"Cold Policy+Value Target:{cold_p:.2f}°C")
print(f"\nModel Q* Search Sensitivity: {abs(hot_p - cold_p):.4f}°C")